[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

; --- FIX RESET HARDWARE USB NATIVA ---
monitor_rts = 0
monitor_dtr = 0
upload_flags =
    --before=default_reset
    --after=hard_reset
upload_port = COM3
; -------------------------------------

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    
    ; --- PIN UART RADAR LD2420 ---
    ; Filo TX dell'ESP -> va al pin OT1 (RX) del radar
    -DGG_TXPIN=5
    ; Filo RX dell'ESP -> va al pin OT2 (TX) del radar (Filo arancio)
    -DGG_RXPIN=4 
    
    -DGG_BAUDRATE=115200
    -DGG_DEBUG=1

lib_deps = 
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    mathieucarbou/AsyncTCP @ ^3.2.14
    bblanchon/ArduinoJson @ ^7.1.0
    gsieben/LD2420GeoGab @ ^1.0.0